"""Add service and user mapping tables

Revision ID: 3f53e68e6e2f
Revises: e0a52889fb79
Create Date: 2025-11-25 22:49:50.247594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f53e68e6e2f'
down_revision: Union[str, None] = 'e0a52889fb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
