"""Add log_entries and alert tables

Revision ID: b330c410dcaa
Revises: 3f53e68e6e2f
Create Date: 2025-11-27 13:12:41.655854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b330c410dcaa'
down_revision: Union[str, None] = '3f53e68e6e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
