"""add alert acknowledgment fields

Revision ID: f2ec3cb56436
Revises: ec1c3fa21321
Create Date: 2026-01-04 08:54:29.814557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ec3cb56436'
down_revision: Union[str, None] = 'ec1c3fa21321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('acknowledged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('alert_history', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alert_history', sa.Column('acknowledged_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_history', 'acknowledged_by')
    op.drop_column('alert_history', 'acknowledged_at')
    op.drop_column('alert_history', 'acknowledged')
    # ### end Alembic commands ###
